---
# File: roles/hostnode/tasks/lxcenv-setup.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description: LXC environment setup
# - setup hostnodes LXC-environment in playbook inventories
# - ensure availability of all required distro packages
# -
# #############################################################################

## Ensure env.* pckgs are installed
# [KohaLXC]: lxcenv: Packages for LXC-environment(s)
- name: lxc - Ensure all needed packages are installed
  become: yes
  apt: >
    name="{{ item }}"
    update_cache="yes"
    state="present"
    autoremove="yes"
  with_flattened:
    - hostnode_lxcenv_pckgs

## [TODO]: LXC networking, DNS, resolvconf, dnsmasq host settings..

## Debug: some lxcenv related networking and domain settings
- debug: var=hostnode_lxcenv_enabled,hostnode_lxcenv_pckgs,hostnode_lxcenv_networking,hostnode_lxcenv_domain

## Create directory with correct permissions for custom localized facts
- name: lxc - Create default directory for custom Ansible/LXC-related facts
  become: yes
  file: |
    path=/etc/{{ item }}
    state=directory
    recurse=yes
    force=yes
    mode="g=rx,o-rwx"
    group="{{ hostnode_kohagrp_name | d('koha') }}"
  with_items:
    - ansible
    - ansible/facts.d

## LXC-containers:
# - retrieve (authorative) list of names of managed LXCs
- include_vars: lxcs/all_lxcs.yaml name=lxcs
- debug: var=lxcs
# - retrieve defaults from 'roles/<role>/vars/lxcs/default'
- include_vars: lxcs/default/config/default.yaml
# LXCs: to be managed/running in inventory host in: $KOHALXC_SETUP
# - use what we have in 'lxc_names':
- name: lxc - Read definitions for all named LXCs
  include_vars:
    file: "lxcs/{{ item }}/config/{{ item.split('.')[0] }}.yaml"
    name: "{{ item.split('.')[0] }}"
  with_items: lxcs.lxcs_names | d()
  when:
    - item is defined and item != ''
    #- (item.split('.')[1] in inventory_hostname)
#- debug: var=hostvars[inventory_hostname]
# - manually like this:
#- include_vars: file=lxcs/kldev_dmdbks.weblxc/config/kldev_dmdbks.yaml name=kldev_dmdbks
#- include_vars: file=lxcs/kltest_dmdb.mdblxc/config/kltest_dmdb.yaml name=kltest_dmdb
#- include_vars: file=lxcs/kltest_mdbks.mdblxc/config/kltest_mdbks.yaml name=kltest_mdbks

## LXC-containers: Combine defined LXCs as fact list
# - if 'lxcs.lxcs_names' doesn't have any of these, the d() takes care of ignoring it
- name: lxc - Combine all read LXC definitions
  set_fact:
    hostnode_lxcs:
      - "{{ kldev_dmdbks|d() }}"
      - "{{ kltest_dmdb|d() }}"
      - "{{ kltest_mdbks|d() }}"

#- debug: var=hostnode_lxcs,hostnode_kohalxc_tooldir,kohalxc_tooldir
## Extract the env enablements from lxc.group's in container_config
# TODO: (remove this): delete *.fact files first -> obsolete, dirs have been cleared previously
#- name: lxcenv - Start LXC-environments facts building with clean state
#  file: |
#    path="{{ hostnode_kohalxc_tooldir}}/conf.d/env.data/lxcs/{{ item.lxc.name | d('default') }}.{{ item.net.domain | d('lxc') }}/config/{{ item.lxc.name | d('default') }}.fact"
#    state=absent
#  with_items: hostnode_lxcs | d()
#  when:
#    - item.net.domain is defined and item.net.domain in inventory_hostname
    
- name: lxc - Extract LXC-environments facts from lxc.group in 'container_config'
  template: >
    src="files/kohalxc_lxcenv/getEnvironmentFromContainerConfig.yaml.j2"
    dest="{{ hostnode_kohalxc_tooldir}}/conf.d/env.data/lxcs/{{ item.lxc.name | d('default') }}.{{ item.net.domain | d('lxc') }}/config/{{ item.lxc.name | d('default') }}.fact"
    force="yes"
  with_items: hostnode_lxcs | d()
  when:
    - item.net.domain is defined and item.net.domain in inventory_hostname

## Show all LXC-containers
- name: lxc - Show all defined LXCs (managed/running in inventory host)
  debug: var=item.net.domain,item.lxc.name,item.lxc.state
  with_items: hostnode_lxcs | d()
  changed_when: false
  when:
    - item is defined
    - item.net is defined
    - item.net.domain is defined and item.net.domain in inventory_hostname

## Ensure that managed LXCs are stopped (if they exists already)
- name: lxc - Ensure managed LXCs are stopped (if they are present)
  become: yes
  shell: "lxc-ls -f --active | grep -q {{ item.lxc.name }} && lxc-stop -n {{ item.lxc.name }} || echo 'Nothing to stop.'"
  args:
    executable: /bin/bash
    chdir: "/home/{{ hostnode_operuser }}"
  with_items: hostnode_lxcs | d()
  when:
    - item is defined
    - item.net is defined
    - item.lxc is defined and item.lxc.name is defined
    - item.net.domain is defined and item.net.domain in inventory_hostname

## Get current date: yyyymmdd
#- set_fact: kohalxc_date_full="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
- set_fact: kohalxc_date_yyyymmdd="{{lookup('pipe','date +%Y%m%d')}}"
## Get current date: day-of-week:
- set_fact: kohalxc_date_dow="{{lookup('pipe','date +%u')}}"
- debug: var=kohalxc_date_yyyymmdd,kohalxc_date_dow

## Backup all managed LXCs now that they are stopped according to backup-schedule
# - weekly for now: day-of-week == 2=Tuesday or 4=Thursday or 7=Sunday)
- name: lxc+backup - Weekly (Tue, Thu, Sun) tar/rsync backup of managed LXC-containers to Backup-server (if not already)
  become: yes
  environment:
    KOHALXC_NAME: "{{ item.lxc.name }}"
    KOHALXC_BACKUP_NAME: "lxcenv-backup_{{ kohalxc_date_yyyymmdd }}"
  shell: |
    [[ "{{ansible_host}}" == "{{hostnode_backupsrv}}" ]] && sudo su -l {{ hostnode_operuser }} -c "[[ ! -d {{ hostnode_backup_backupdir }}/${KOHALXC_BACKUP_NAME} ]] && mkdir -p {{ hostnode_backup_backupdir }}/${KOHALXC_BACKUP_NAME}" || exit 0 &&
    tar --numeric-owner -czf /tmp/${KOHALXC_NAME}.{{item.net.domain}}.tar.gz /var/lib/lxc/${KOHALXC_NAME} &&
    [[ "{{ansible_host}}" != "{{hostnode_backupsrv}}" ]] && sudo su -l {{ hostnode_operuser }} -c "scp /tmp/${KOHALXC_NAME}.{{ item.net.domain }}.tar.gz {{ hostnode_operuser }}@{{ hostnode_backupsrv }}:{{ hostnode_backup_backupdir }}/${KOHALXC_BACKUP_NAME}/." ||
    cp -v /tmp/${KOHALXC_NAME}.{{ item.net.domain }}.tar.gz {{ hostnode_backup_backupdir }}/${KOHALXC_BACKUP_NAME}/.;
    rm -f -r /tmp/${KOHALXC_NAME}.{{item.net.domain}}.tar.gz
  #export CN=koha_mdbks316 && kohalxc -n ${CN:-default} stop && sudo tar --numeric-owner -czf /tmp/${CN}.tar.gz /var/lib/lxc/${CN} && sudo rsync -avzhe ssh --progress --remove-source-files /tmp/${CN}.tar.gz jukka@roi2.netum.fi:/Backup/tes
  args:
    executable: /bin/bash
    creates: "{{ hostnode_backup_backupdir }}/lxcenv-backup_{{ kohalxc_date_yyyymmdd }}/{{ item.lxc.name }}.tar.gz"
  with_items: hostnode_lxcs | d()
  when:
    - hostnode_backup_enabled
    - (kohalxc_date_dow|int == 2) or (kohalxc_date_dow|int == 4) or (kohalxc_date_dow|int == 7)
    - item is defined and item.net is defined
    - item.net.domain is defined and item.net.domain in inventory_hostname
    - item.lxc is defined and item.lxc.name is defined
    - hostnode_backupsrv is defined and hostnode_backup_backupdir is defined

- debug: var=hostnode_dataenv_enabled,hostnode_kohalxc_organization,hostnode_dataenv_dataset,hostnode_kohalxc_works
##  Use this to resolve need for manually mount devenv/convlog dirs
# - for browsing and migration/LXCs (in non 'dataenv' hostnodes)
- name: non-data(sshfs) - Mount datenv hosts folders for 'kohadata'
  #become: yes
  environment:
    SSHPASS: "{{hostnode_operpass}}"
  shell: |
    sshpass -e ssh-copy-id -o 'StrictHostKeyChecking=no' -i /home/{{hostnode_operuser}}/.ssh/id_rsa.pub {{hostnode_operuser}}@{{hostnode_websrv}}
    (cd {{hostnode_kohalxc_works}}/{{hostnode_kohalxc_organization}}/kohadata &&
    mkdir -vp dump4mmt-convsource && chmod g+w dump4mmt-convsource &&
    [[ ! -e dump4mmt-default ]] && ln -s dump4mmt-convsource dump4mmt-default;
    [[ ! -d dump4mmt-convsource/logs ]] && sshfs -o allow_other,reconnect {{hostnode_operuser}}@{{hostnode_websrv}}:Works/{{hostnode_kohalxc_organization}}/kohadata/dump4mmt-default/source.0/ {{hostnode_kohalxc_works}}/{{hostnode_kohalxc_organization}}/kohadata/dump4mmt-convsource;
    ls -l dump4mmt-default/ && echo "== All done.")
  args:
    executable: /bin/bash
  when:
    - not hostnode_dataenv_enabled

- name: non-data - Mount access for Koha-staff to dump4default-convsources (if any)
  become: yes
  shell: |
    [[ -d {{hostnode_kohalxc_works}}/{{hostnode_kohalxc_organization}}/kohadata/dump4mmt-convsource ]] && ( rm -f /home/koha/{dumpdefault,konversiolokit,virkailijakirjeet} &&
    ln -f -s {{hostnode_kohalxc_works}}/{{hostnode_kohalxc_organization}}/kohadata/dump4mmt-convsource /home/koha/dumpdefault &&
    ln -f -s {{hostnode_kohalxc_works}}/{{hostnode_kohalxc_organization}}/kohadata/dump4mmt-convsource/logs /home/koha/konversiolokit &&
    ln -f -s {{hostnode_kohalxc_works}}/{{hostnode_kohalxc_organization}}/kohadata/dump4mmt-convsource/target/Patrons/staffaccounts/letters /home/koha/virkailijakirjeet &&
    echo "== All symlinks done.")
    exit 0
  args:
    executable: /bin/bash
  when:
    - not hostnode_dataenv_enabled

## Create/re-configure and enable all LXCs
# - do this only in remote 'development' and 'testing'
- name: lxc - Create/re-configure all defined LXCs
  become: yes
  lxc_container:
    "{{ item.lxc }}"
  with_items: hostnode_lxcs | d()
  register: cmd_lxccreate
  when:
    - item is defined
    - item.lxc is defined
    - item.net is defined
    - item.lxc.container_config is defined
    - item.net.domain is defined and item.net.domain in inventory_hostname

#- debug: var=cmd_lxccreate.results
## TODO: Ensure that hostnode ssh-key has been copied to managed LXC
- name: lxc - Ensure host is authorized to PK-access in managed LXCs
  environment:
    LXCHOST: "{{ item.lxc_container.name }}.{{ item.item.net.domain }}"
    LXCUSER: "{{ item.item.net.user | d('ubuntu') }}"
    SSHPASS: "{{ kohalxc_operpass }}"
  shell: sshpass -e ssh-copy-id -i .ssh/id_rsa.pub $LXCUSER@$LXCHOST
  no_log: True
  with_items: cmd_lxccreate.results
  when:
    - item.lxc_container is defined and item.lxc_container.state == "running"
    - item.item.net is defined
    - item.item.net.domain is defined and item.item.net.domain in inventory_hostname

## Check whether we have auth/host-key for sshing to LXCs
- name: lxc - Has control host auth/host-key for jump-sshing to remote LXCs
  #debug: var=item.lxc_container.name,item.item.net.domain,item.lxc_container.state
  environment:
    LXCHOST: "{{item.lxc_container.name}}.{{item.item.net.domain}}"
  shell: ssh-keygen -l -F "$LXCHOST" > /dev/null || echo "$LXCHOST"
  with_items: cmd_lxccreate.results
  register: cmd_sshkeys_missing
  when:
    - item.lxc_container is defined and item.lxc_container.state == "running"
    - item.item.net is defined
    - item.item.net.domain is defined and item.item.net.domain in inventory_hostname
  delegate_to: localhost

#- debug: var=cmd_sshkeys_missing.results,kohalxc_operuser,hostnode_sshport
## Ensure control host/user auth key is present for jump-sshing to remote LXCs
# - relevant parts copied from kohahosts/lxcenv-setup.yaml (222)
# - above check based on 'known_hosts' entry in control host, not the key in LXCS
# - pass only to runnning LXCs (in respective hosts) whose keys are missing
- name: lxc - Pass control host/user auth-key for jump-sshing to remote LXCs
  environment:
    LXCHOST: "{{ item.stdout }}"
    LXCUSER: "{{ item.item.item.net.user | d(kohalxc_operuser) }}"
    SSHPASS: "{{ kohalxc_operpass }}"
  shell: sshpass -e ssh-copy-id -o 'StrictHostKeyChecking=no' -o 'ProxyCommand=ssh -q {{ hostnode_operuser }}@{{ ansible_host }} -p {{ hostnode_sshport }} -W %h:%p' -i {{ local_home }}/.ssh/id_rsa.pub $LXCUSER@$LXCHOST
  #debug: msg="item.stdout={{item.stdout}},item.item.item.net.usr={{item.item.item.net.user}},sshpass -e ssh-copy-id -o 'StrictHostKeyChecking=no' -o 'ProxyCommand=ssh -q {{ hostnode_operuser }}@{{ ansible_host }} -p {{ hostnode_sshport }} -W %h:%p' -i {{ local_home }}/.ssh/id_rsa.pub $LXCUSER@$LXCHOST"
  #shell: echo sshpass -e ssh-copy-id -o 'StrictHostKeyChecking=no' -o 'ProxyCommand=ssh -q {{ hostnode_operuser }}@{{ ansible_host }} -p {{ hostnode_sshport }} -W %h:%p' -i {{ local_home }}/.ssh/id_rsa.pub {{ kohalxc_operuser }}@$LXCHOST
  #no_log: True
  with_items: cmd_sshkeys_missing.results
  when:
    - item is defined
    - item.stdout is defined and item.stdout != ''
    - item.item is defined and item.item.item is defined and item.item.item.net is defined
    - item.item.item.net.user is defined
  delegate_to: localhost

## Show the status of existing LXCs..
- name: lxc - status/setup - List status of running/stopped LXCs..
  become: yes
  shell: lxc-ls -f


## Abort play here (for testing and development):
#- fail:
