---
# File: roles/hostnode/tasks/main.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description:
# - provisioning of koha-related server/hostnodes in playbook inventories 
# ##############################################################################

## General: debug,status,setup,..
- include: hostnode-debug.yaml
  tags: hostnode:debug
#- include: hostnode-status.yaml
#  tags: hostnode, hostnode:status
#- include: hostnode-setup.yaml
#  tags: hostnode, hostnode:setup

## srvenv-{status,setup}
- include: srvenv-status.yaml
  tags: hostnode,hostnode:status,hostnode:srvenv-status
- include: srvenv-setup.yaml
  tags: hostnode,hostnode:setup,hostnode:srvenv-setup
  when: hostnode_srvenv_enabled

## dataenv-{status,setup}
#- include: dataenv-status.yaml
#  tags: hostnode,hostnode:status,hostnode:dataenv-status
- include: dataenv-setup.yaml
  tags: hostnode,hostnode:setup,hostnode:dataenv-setup
  when: hostnode_dataenv_enabled

## secure-{status,setup}
#- include: secure-setup.yaml
#  tags: hostnode,hostnode:setup,hostnode:secure-setup
#  when: hostnode_secure_enabled

## devenv-{status,setup}

## lxcenv-{status,setup}
#- include: lxcenv-status.yaml
#  tags: hostnode, hostnode:lxcenv, hostnode:lxcenv-status
- include: lxcenv-setup.yaml
  when: hostnode_lxcenv_enabled
  tags: hostnode, hostnode:lxcenv, hostnode:lxcenv-setup

## mdbenv-{status,setup}

## webenv-{status,setup}

## TODO: Do wee need to flush handlers as the last step of each role?
#- meta: flush_handlers
