---
# File: roles/hostnode/tasks/srvenv-status.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description: "srvenv-status"
# - status of the hostnodes server-environment in playbook inventories
# - OS, distro, kernel
# - timezone, localizations
# - filesystems: lvm, btrfs, zfs
# - network: iptables rules
# - apt packages: upgrade and update settings
# ##############################################################################

## Show server lsb and os release and kernel details
- name: Show server lsb and os release details
  shell: cat /etc/lsb-release && cat /etc/os-release && uname -a
  changed_when: false

## Localizations: timezone
- name: Show server timezone
  become: yes
  shell: timedatectl || dpkg-reconfigure -f noninteractive tzdata
  changed_when: false

## Show: LVM Physical Volume (PV) attributes 
- name:  Show attributes of LVM-Physical volume (PV), if any
  become: yes
  command: pvdisplay -m -v
  when: hostnode_lvm_enabled
  changed_when: false

## Show: ZFS and zpool status and attributes 
- name:  Show status of server support for ZFS/zpools
  become: yes
  shell: zpool list && zpool status && zpool get all && zfs list
  when: hostnode_zfs_enabled
  changed_when: false

## Show filesystems support: btrfs
- name: Show server filesystem support for 'btrfs'
  shell: btrfs help | grep -A1 "btrfs help" 2>&1
  register: cmd_btrfs
  when: hostnode_btrfs_enabled | d()
  failed_when: cmd_btrfs.rc != 0
  changed_when: false
  
## Show: iptables rules
- name: Show server/host iptables rules
  become: yes
  command: iptables -L -v -n -t nat
  register: cmd_iptables
  changed_when: false

## Packages: update/upgrade server settings
- name: Show server packages auto update & unattended upgrades settings
  shell: echo "== /etc/apt/apt.conf.d/20auto-upgrades ==" && cat /etc/apt/apt.conf.d/20auto-upgrades | grep -v "//\|#"; echo "== /etc/apt/apt.conf.d/50unattended-upgrades ==" && cat /etc/apt/apt.conf.d/50unattended-upgrades | grep -v "//\|#"
  changed_when: false

## Show packages that are upgradable
- name: Show what can be updated (sans held/ignored packages)
  shell:  apt list --upgradeable 2>/dev/null | grep -v "{{ hostnode_upgrade_pckgsignore | d()}}" | grep -s "upgradable"
  register: cmd_apt
  failed_when: cmd_apt.stderr != ""
  changed_when: cmd_apt.rc == 0

## Show servers rebootability and upgradability status (+ dataenv status)
- debug: var=hostnode_upgrade_enabled,hostnode_reboot_enabled,hostnode_dataenv_enabled
