---
# File: inventory/development/group_vars/all/main.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description: group_vars defauls @ 'development' inventory 
# - overrides role-settings
# - will be overwritten by playbook-level 'group_vars/all/{main,vault}.yaml'
# - settings in 'hosts, 'vault.yaml', 'host_vars' here override all these
# #############################################################################

## #####################################
## General: facts & handlers + inventory
## #####################################

# Inventory: localdev, 'development', testing, production
hostnode_environment: "{{ inventory_dir | basename }}"
# Testing/debugging vars inheritance in ansible:
hostnode_testvar: inventory_development_group_vars_all

# Facts gathering:
gather_facts: False
# Force all handlers always (also in case play fails..)
#force_handlers: False


## ########################
## General: Ansible-related
## ########################

# Python interpreter:
# - for distros not having Python 2 in path (e.g 'Ubuntu 16.04')
#ansible_python_interpreter: /usr/bin/python2.7
# Ansible_connection: ssh/local
ansible_connection: ssh
# Ansible_port:
ansible_port: "{{ hostnode_sshport | d('22') }}"
# Ansible_user:
ansible_user: "{{ hostnode_operuser | d('kohaoper') }}"
# Ansible become method:
#ansible_become_method: sudo
# Asible_become_pass:
ansible_become_pass: "{{ hostnode_operpass }}"


## ###############################
## KohaLXC/dataenv: datasets+fixes
## ###############################

## Data and dumps for MMT
hostnode_dataenv_enabled: False
#hostnode_dataenv_pckgs:
#hostnode_dataenv_confdir:
#hostnode_dataenv_datadir:
# Data/set names and fixes in source dirs
hostnode_dataenv_datasets:


## ################################################
## KohaLXC/srvenv: updates, networking, filesystems
## ################################################

## Server/host management and networking
# Rebootable server:
hostnode_reboot_enabled: False
# Upgradable server:
hostnode_upgrade_enabled: True
# List of (wildcarded) package names ignored in upgrades
hostnode_upgrade_pckgsignore: "bacula-"
# Network interface:
hostnode_network_interface: bond0

## Server/host filesystem: LVM-storage
hostnode_lvm_enabled: False
# Volume group (VG) name (main):
hostnode_lvmvg_main: roi-vg

## Server/host filesystem: ZFS-storage
# ZFS support:
hostnode_zfs_enabled: False


## ############################################
## KohaLXC/lxcenv: host systems LXC-environment
## ############################################

## Server/host LXC/LXD packages and paths
# (enabled here only for 'testing' and 'production' inventories)
hostnode_lxcenv_enabled: False
# (disabled here for LXD 2.0 having serious issues with zpool/ZFS)
hostnode_lxdenv_enabled: False
#hostnode_lxcenv_pckgs:
#hostnode_lxcenv_confdir:
#hostnode_lxcenv_setupdir:

## Server/host LXC-networking
# Naming/discovery: manual (configured) / dynamic (dhcp)
hostnode_lxcenv_networking: manual
# Naming/domain: none, lxc, kohalxc, weblxc, mdblxc
hostnode_lxcenv_domain: "{{ (hostnode_lxcenv_networking == 'dhcp') | ternary('kohalxc','lxc') }}"

## List of LXCs: defaults and templates
# (can contain both web and db-related LXCs for all hosts)
hostnode_lxcenv_lxcs:
hostnode_lxcs:


## #############################################
## KohaLXC/kohaenv: Koha/webapp-related settings
## #############################################

## Koha/webapp settings:
# Koha/webapp server domain (DNS):
hostnode_kohaenv_srvdomain: lapinkirjasto.fi
# Koha/webapp server name (DNS)
#hostnode_kohaenv_srvname: *.lapinkirjasto.fi
# Koha/webapp SSL/DNS-01 challange
#hostnode_kohaenv_ssl_acmechallenge:
