---
# File: group_vars/all/main.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description:
# - list here all playbook-level 'group_vars' used in inventories/roles setups
# - setting them here will override values in inventories and roles!!!
# - vars defined in encrypted group_vars/all/vault.yaml override all here
#
# See also:
# - inventory/<hostnode_environment>/hosts
# - inventory/<hostnode_environment>/group_vars/{main,vault}.yaml
# #############################################################################

## ###########################
## General: facts & hanldlers
## ###########################
# Facts gathering:
#gather_facts: False
# Force all handlers always (also in case play fails etc):
#force_handlers: false

## ###############
## Ansible related
## ###############
## ! don't define vars that are to be set in inventories/roles per group/host !
# Python interpreter:
# - set for distros that don't have Python 2 in path (e.g 'Ubuntu 16.04')
ansible_python_interpreter: /usr/bin/python2.7
# Ansible_connection: ssh/local
#ansible_connection: ssh
# Ansible_port:
#ansible_port: "{{ hostnode_sshport | d('22') }}"
# Ansible become method:
ansible_become_method: sudo
# Ansible_user:
#ansible_user: "{{ hostnode_operuser | d(kohaoper) }}"
# Ansible become pass':
#ansible_become_pass
# Ansible SSH common arguments
# - e.g. proxy-command to access containers directly from control host..
#ansible_ssh_common_args:

# ############################################################
# Vault/secure settings:
# - list here all encrypted variable names needed by the play
# - use '*vault*.yaml' etc. (won't be included in this repo)
# ############################################################

## Accessing Koha/LXC-containers
# - operations user name (could be overriden in lxc-create):
#kohalxc_operuser: ubuntu
# - operations user pass:
#kohalxc_operpass:

## KohaLXC: "devenv", "mdbenv", "kohaenv" users/passes/configs
# MariaDB/Mysql-database root user name:
kohalxc_mdbenv_rootuser: root
# MariaDB/Mysql-database root user pass:
kohalxc_mdbenv_rootpass:
# Database koha-user name:
kohalxc_mdbenv_kohauser:
# Database koha-user pass
kohalxc_mdbenv_kohapass:
# Database name for koha-data: 'kohadata'
kohalxc_mdbenv_kohadb:

## Settings in 'testing'/'production' for 'hostnode'/severs
# Server name of "koha" web/applications and services:
hostnode_websrv:
# Server name of "koha" databases and services:
hostnode_mdbsrv:
# Server name of "koha" data/mmt storage/utilities:
hostnode_datasrv:

# Koha-system user name: 'kohasys'
hostnode_kohasys_user:
# Koha-system user id: '1000'
hostnode_kohasys_id:
# Koha-system user pass:
hostnode_kohasys_pass:

# Koha-group name: 'kohagrp'
hostnode_kohagrp_name:
# Koha-group gid: '1001'
hostnode_kohagrp_gid:

# Koha-devops user name: 'kohaoper'
hostnode_operuser:
# Koha-devops user id: '1002'
hostnode_operid:
# Koha-devops pass:
#hostnode_operpass:
