#!/usr/bin/env ansible-playbook
---
# File: $KOHALXC_ANSIBLE_ROOTDIR/kohalappi/kohalappi-all.yaml
# #############################################################################
# Code is part of KohaLXC/kohatools Ansible/Bash tooling environment  
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description/notes/usage:
# - requires Ansible version 2.2.0 (should be in /usr/local/bin/ansible using)
# - config file = $KOHALXC_ANSIBLE_ROOTDIR/kohalappi/ansible.cfg
# - inventories: e.g -i localdev (asx default in 'ansible.cfg')
# - [TODO: following gguide is outdated and should be updated]
#  1a) Basic use:
#   "cd $KOHALXC_ANSIBLE_ROOTDIR/kohalappi; ansible-playbook kohalappi-all.yaml"
#  1b) Basic use (sub-shell in $KOHALXC_ANSIBLE_ROOTDIR/<ansible play>/):
#     (cd $KOHALXC_ANSIBLE_ROOTDIR/kohalappi; ansible-playbook kohalappi-all.yaml)
#  2a) Run for 'kohahosts' only (needs sudo-pass dev/host: 'kohadev@kohahost'):
#    (cd $KOHALXC_ANSIBLE_ROOTDIR/kohalappi; \
#     ansible-playbook -K -l kohahosts kohalappi-all.yaml)"
#  2b) Run for 'kohalxs' only (needs sudo-pass for dev/lxc: 'kohalxc_operuser@kohalxc_name'):
#    (cd $KOHALXC_ANSIBLE_ROOTDIR/kohalappi; \
#     ansible-playbook -K -l kohalxcs kohalappi-all.yaml)"
# Also ad-hoc ansible commands work (cd here):
#  3a) ansible -i localdev --vault-password-file .vault.pass.txt -m ping all
#  3b) ansible -i testing --vault-password-file .vault.pass.txt -m ping kohahosts
# ############################################################################

## Include Koha-server plays: LXC-hosts with dev/srv/web/mdb/dataenv(s)
- include: kohalappi-kohasrv.yaml

## Include Koha-LXC plays: LXC-guests with web(koha)/mdb/dataenv(s)
- include: kohalappi-kohalxc.yaml
