---
# File: inventory/localdev/group_vars/all/main.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description: group_vars defaults @ 'localdev' inventory
# - overrides role-settings,
# - will be overwritten by playnook-level 'group_vars/all/{main,vault}.yaml'
# - settings in 'hosts', 'vault.yaml' and 'host_vars' here override all these
# #############################################################################

## #####################################
## General: facts & handlers + inventory
## #####################################

# Inventory: 'localdev', development, testing, production
hostnode_environment: "{{ inventory_dir | basename }}"
# Testing/debugging vars inheritance in ansible:
hostnode_testvar: inventory_localdev_group_vars_all_main

# Facts gathering:
#gather_facts: False
# Force all handlers always (also in case play fails..)
#force_handlers: False


## ########################
## General: Ansible-related
## ########################
#ansible_python_interpreter
#ansible_connection
#ansible_port
#ansible_user
#ansible_become_method
#ansible_become_pass


## ##########################
## Server: connectivity/users
## ##########################

## Provide below 'hostnode'-vars in ./vault.yaml:
# SSH_port:
#hostnode_sshport: 22
# Oper user id
#hostnode_operid:
# Oper user name
#hostnode_operuser:
# Oper user pass
#hostnode_operpass:


## ################################################
## KohaLXC/srvenv: updates, networking, filesystems
## ################################################

## Server/host management and networking
# Rebootable server:
hostnode_reboot_enabled: False
# Upgradable server:
hostnode_upgrade_enabled: True
# List of (wildcarded) package names ignored in upgrades
#hostnode_upgrade_pckgsignore: "bacula-"
# Network interface:
hostnode_network_interface: eth0

## Server/host filesystem: LVM-storage

## Server/host filesystem: ZFS-storage


## ############################################
## KohaLXC/lxcenv: host systems LXC-environment
## ############################################

## Server/host LXC/LXD packages and paths

## Server/host LXC-networking

## List of LXCs: defaults and templates


## #############################################
## KohaLXC/kohaenv: Koha/webapp-related settings
## #############################################

## Koha/webapp settings:
# Koha/webapp server domain (DNS):
#hostnode_kohaenv_srvdomain: localdomain
# Koha/webapp server name (DNS)
#hostnode_kohaenv_srvname: localhost.localdomain
# Koha/webapp SSL/DNS-01 challange
#hostnode_kohaenv_ssl_acmechallenge:
