---
# File: lxcs/kltest_dmdb.mdblxc/config/kltest_dmdb.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
#
# Description:
# - LXC-name: 'kltest_dmdb.mdblxc'
# - kltest: KohaLappi/testing, Ubuntu/Trusty, dir, lxcbr0/NAT
# - dmdb: data/MMT-conversion + MariaDB
# - mdblxc: deploy to host serving '*mdblxc'-domains
# - network: (web)app[OPAC]-port=8*, (web)int[STAFF]-port=808*
# #############################################################################

## network port LXC/host port mappings + domain:
# - (web/mdb)lxc => host: 8*/808* => 80/8080
net:
  domain: mdblxc
  user: "{{ kohalxc_operuser }}"
##  lxc: MariaDb (mdbenv), data/MMT (dataenv)
# - for MMT/conversion etc. (testing, dhcp/mdblxc)
lxc:
  name: kltest_dmdb
  state: started
  backing_store: "{{ lxc_default.backing_store }}"
  container_log: "{{ lxc_default.container_log }}"
  container_log_level: "{{ lxc_default.container_log_level }}"
  container_config: 
    # lxc/mounts
    - "{{ hostnode_lxc_mount_kohatools }}"
    - "{{ hostnode_lxc_mount_kohadata }}"
    # lxc/group
    - lxc.group = {{ hostnode_environment | d('local') }}
    - lxc.group = dev
    - lxc.group = mdb
    - lxc.group = ppmmt
    # lxc/start
    - lxc.start.auto = 1
    - lxc.start.delay = 0
    # lxc/network
    - lxc.network.veth.pair = Vkltest_dmdb
    - lxc.network.type = veth
    - lxc.network.link = lxcbr0
    - lxc.network.flags = up
  template: "{{ lxc_default.template }}"
  template_options: >
    --user {{ kohalxc_operuser }}
    {{ lxc_default.template_options }}
  container_command:
    "{{ lxc_default.container_command + hostnode_mdbenv_pckginstall }}"
