---
# File: roles/kohalxcs/tasks/kohaenv-setup.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description: setup tasks of Koha/webapp-related LXCs
# - setup Koha-related LXCs environments in all playbook inventories
# - ensure availability of all required distro packages and Perl-modules
# - etc. etc.
# ##############################################################################

#- debug: var=kohalxcs_devenv_enabled,kohalxcs_dataenv_enabled,kohalxcs_mdbenv_enabled,kohalxcs_kohaenv_enabled,kohalxcs_kohaenv_srvname

## Koha-community repo, release and APT-keys
- name: koha - Add Koha-community APT packages repository and keys
  become: yes
  shell: |
    echo "deb {{ kohalxcs_kohaenv_repo }} {{ kohalxcs_kohaenv_release }}" > {{ kohalxcs_kohaenv_aptlist }}
    # Retrieve repo signing key (if OS has not already)
    [[ $(apt-key list | grep -s 'koha-community') ]] || wget -O- {{ kohalxcs_kohaenv_repo }}/gpg.asc | apt-key add -
    # Show what we got
    cat {{ kohalxcs_kohaenv_aptlist }}
    apt-key list | grep -B1 -A2 'koha-community'
  args:
    executable: /bin/bash
  when:
    - kohalxcs_kohaenv_enabled

## Clone/checkout Koha source Git repository (standard/dev KS-3.16)
- name: koha - Clone/checkout clean Koha source Git repo (dev/KS-3.16)
  git:
    repo: "{{ kohalxcs_kohaenv_gitrepo }}"
    dest: "{{ kohalxcs_kohaenv_kohaclone }}"
    clone: yes
    update: yes
    force: yes
  when:
    - kohalxcs_kohaenv_enabled

##
## TODO/FIX: Rest of Koha-installation steps
##

## Checkout one specified patch/commit/branch from Koha source Git repository
- name: koha - Checkout specified version (commit/patch) from Git..
  git:
    repo: "{{ kohalxcs_kohaenv_gitrepo }}"
    dest: "{{ kohalxcs_kohaenv_kohaclone }}"
    version: "{{ kohalxcs_kohaenv_gitpatch }}"
    clone: no
    update: no
  register: cmd_gitcheckout_patchcommit
  when:
    - kohalxcs_kohaenv_enabled
    - kohalxcs_kohaenv_gitpatch is defined
- debug: var=cmd_gitcheckout_patchcommit

- include_vars: kohaenv-setup.yaml
- debug: var=kohalxcs_kohaenv_gitpatches
## Format and apply Git-based patches to Koha-source/code
- name: koha - Apply Git-based patches to Koha source and installation
  environment:
    KOHALXC_PATCH_FORMATCMD: "{{ item.patch | d('echo') }}"
    KOHALXC_PATCH_APPLYCMD: "patch --verbose -p1 -b -i 0001-{{ item.name }}-{{ item.desc }}.patch"
  shell: |
    pwd && [[ -d "{{ item.dir }}" ]] && (
    cd {{ item.dir }} && $KOHALXC_PATCH_FORMATCMD && $KOHALXC_PATCH_APPLYCMD )
  args:
    executable: /bin/bash
    chdir: "{{item.dir}}"
    creates: "0001-{{item.name}}-{{item.desc}}.patch"
  with_items: "{{ kohalxcs_kohaenv_gitpatches | d() }}"
  register: cmd_gitpatch
  when:
    - kohalxcs_kohaenv_enabled
    - kohalxcs_kohaenv_gitpatches is defined
    - kohalxcs_kohaenv_gitpatch is not defined

- debug: var=cmd_gitpatch
## Copy Git-dev/source tree patches/tweaks to Koha-installation dir(s):
# - patch KD#1452 (only for english UI)
- name: koha - Modify Koha-install by the above Git-dev/source patches
  become: yes
  shell: |
    pwd &&
    [[ -f $(echo 0001-{{item.name}}-*.patch) && ! -f $(echo 0001-{{item.name}}-*.patch.done) ]] || echo "== kohalxc_ansible: Patch '0001-${{item.name}}-...patch' does not exist or already applied." && (
    cp -vpb {{item.srcdir}}/{{item.file}} {{item.destdir}}/{{item.file}} &&
    for f in 0001-{{item.name}}-*.patch; do cp -vp $f ${f/patch/patch.done}; done &&
    chown {{ kohalxc_kohagrp_name }}:{{kohalxc_kohagrp_name}} {{item.destdir}}/{{item.file}} )
  args:
    executable: /bin/bash
    chdir: "{{ kohalxcs_kohaenv_kohaclone }}-oldstable"
  with_items:
    - { name: "KD-1452",
        srcdir: "koha-tmpl", destdir: "{{kohalxcs_kohaenv_staff_docroot}}",
        file: "intranet-tmpl/prog/en/modules/admin/preferences/patrons.pref" }
    - { name: "KD-1452",
        srcdir: "koha-tmpl", destdir: "{{kohalxcs_kohaenv_staff_docroot}}",
        file: "intranet-tmpl/prog/en/modules/members/memberentrygen.tt" }
    - { name: "KD-1452",
        srcdir: ".", destdir: "{{kohalxcs_kohaenv_staff_cgikoha}}",
        file: "members/memberentry.pl" }
  when:
    - not cmd_gitpatch|skipped and cmd_gitpatch|changed
    - kohalxcs_kohaenv_enabled
    - kohalxcs_kohaenv_gitpatches is defined
    - kohalxcs_kohaenv_gitpatch is not defined
