---
# File: roles/kohalxcs/tasks/kohalxcs-status.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description:
# - status and details of Koha-related LXCs for all inventories 
# ##############################################################################

## Welcome to kohalxcs..
- name: status - Welcome '{{ hostnode_operuser }}' to kohalxcs/status..
  shell: |
    uname -a
    grep a
    whoami
    pwd
    ls -la
    history
    #echo "inventory_hostname={{inventory_hostname}}, ansible_host={{ansible_host}}, ansible_user={{ansible_user}}"
    #dpkg -l {{ kohalxcs_devenv_pckgs | d('bash') }} 
  args:
    executable: /bin/bash
  ignore_errors: yes

## Initialize+reload local facts (mostly for environment enablement of LXCs)
- name: status - Create directory for custom facts
  become: yes
  file: |
    path=/etc/ansible/facts.d
    state=directory
    recurse=yes
- name: status - Set default custom facts (for this role)
  become: yes
  template: |
    src=files/kohalxcs.fact
    dest=/etc/ansible/facts.d
    force=yes
- name: status - Reload default/custom facts (ansible_local.kohalxcs)
  setup: filter=ansible_local
- debug: var=ansible_local.kohalxcs.default,ansible_local.kohalxcs.default.devenv_enabled,ansible_local.kohalxcs.default.dataenv_enabled,ansible_local.kohalxcs.default.mmtenv_enabled,ansible_local.kohalxcs.default.mdbenv_enabled,ansible_local.kohalxcs.default.kohaenv_enabled

## Extract the environment enablements from lxc.group(s)
#- name: status - Extract KohaLXC environment enablements from lxc.group(s)
#  become: yes
#  shell:
#  shell: lxc-info --name=`echo {{ inventory_hostname }} | cut -d"." -f1` -c lxc.group | tr "\n" " " | cut -d"=" -f2- | cut -c2- | sed 's/{{ hostnode_environment }} //'

## Some vars: status/debug 
#- debug: var=hostnode_operuser,kohalxc_operuser
#- debug: var=ansible_host,ansible_user,ansible_host,inventory_hostname
#- debug: var=hostnode_srvname
#- debug: var=hostnode_lxcs
#- debug: var=kohalxcs_devenv_enabled,kohalxcs_dataenv_enabled,kohalxcs_mdbenv_enabled,kohalxcs_kohaenv_enabled


## [TODO]: Do we need the below here? ##

## List all the containers: lxc-ls
#- name: List all containers in kohahosts_srvname={{ kohahosts_srvname }}
#  become: yes
#  command: lxc-ls -f

##########################
## Get the container IPs
##########################
#- name: Get LXC-containers info now that IPs should be available for {{ ansible_host }}
#  become: yes
#  lxc_container:
#    name: "{{ item.key }}"
#  with_dict: "{{ kohahosts_lxcs }}" 
#  register: lxcs_info
#  when: kohahosts_lxcs is defined
