---
# File: roles/kohalxcs/tasks/kohalxcs-status.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description:
# - status and details of Koha-related LXCs for all inventories 
# ##############################################################################

## Welcome to kohalxcs..
- name: status - Welcome '{{ hostnode_operuser }}' to kohalxcs/status..
  shell: |
    uname -a
    grep a
    whoami
    pwd
    ls -la
    history
    #echo "inventory_hostname={{inventory_hostname}}, ansible_host={{ansible_host}}, ansible_user={{ansible_user}}"
    #dpkg -l {{ kohalxcs_devenv_pckgs | d('bash') }} 
  args:
    executable: /bin/bash
  ignore_errors: yes

## TODO: Initialize+reload local facts
# - mostly for environment enablement of LXCs

## Set the kohalxcs defaults as localized ansible facts
# - TODO: this requires the folder /etc/ansible/facts.d to have been created
# - TODO: is this even needed -> commenting out for now!
#- name: status - Set default custom facts (for this role)
#  become: yes
#  template: |
#    src=files/kohalxcs.fact
#    dest=/etc/ansible/facts.d
#    force=yes

# Load kohalxcs environment defaults as localized ansible facts
- name: status - Reload default/custom facts (ansible_local.kohalxcs)
  setup: >
    fact_path="{{ kohalxcs_kohalxc_tooldir }}/conf.d/env.data/lxcs/{{inventory_hostname}}/config"
    filter="ansible_local"
- debug: var=ansible_local
#- debug: var=ansible_host,inventory_hostname,kohalxcs_devenv_enabled,kohalxcs_dataenv_enabled,kohalxcs_mmtenv_enabled,kohalxcs_ppmmtenv_enabled,kohalxcs_mdbvenv_enabled,kohalxcs_kohaenv_enabled

## Some status info about kohalxcs/kohaenvs.
- name: status/koha - Info about kohalxcs/kohaenvs..
  shell: |
    [[ -f {{ kohalxcs_kohaenv_aptlist }} ]] && cat {{ kohalxcs_kohaenv_aptlist }}
    echo "Pckgs: {{ kohalxcs_kohaenv_repo }} {{ kohalxcs_kohaenv_release }}"
    echo "Gito: {{ kohalxcs_kohaenv_gitrepo }}"
    echo "Koha-clone: {{ kohalxcs_kohaenv_kohaclone }}"
    echo "Git-version: {{ kohalxcs_kohaenv_gitpatch | d() }}"
    echo "Git-patches: {{ kohalxcs_kohaenv_gitpatches | d() }}"
  args:
    executable: /bin/bash
  when:
    - kohalxcs_kohaenv_enabled
