---
# File: roles/kohalxcs/tasks/kohalxcs-setup.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description: setup tasks of Koha-related LXCs for dev/mdb/web/data envs
# - setup Koha-related LXCs environments in playbook inventories
# - ensure availability of all required distro packages and Perl-modules
# - 
# ##############################################################################

## Ensure env.* pckgs are installed
# [KohaLXC]: kohalxcs: Packages for LXCs
- name: devenv/dataenv - Ensure all development and data environemnt packages are installed
  become: yes
  apt: >
    name="{{ item }}"
    update_cache="yes"
    state="present"
    autoremove="yes"
  with_flattened:
    - kohalxcs_devenv_pckgs
    - kohalxcs_dataenv_pckgs
  when:
    - kohalxcs_devenv_enabled
    - kohalxcs_dataenv_enabled

- debug: var=hostnode_environment,kohalxc_install,kohalxc_organization
## Setup remote developer environment shell profile (devenv/bash-profile)
# - [TODO]: KOHALXC_ vars have wrong paths (mounts are not in Works but in HOME)
- name: devenv - Setup system-wide Bash profile for KohaLXC-development
  become: yes
  template: >
    src="files/devenv/bash_profile.sh.j2"
    dest="/etc/profile.d/kohalxc-devenv.sh"
    backup="no"
  when:
    - kohalxcs_devenv_enabled
    - hostnode_environment != "localdev"

- debug: var=kohalxcs_kohalxc_tooldir
- fail: 
## Push/copy 'run_conversion' script to ConversionTools
- name: dataenv - Push containerized conversion main script to ConversionTools
  #become: yes
  template: >
    src="files/dataenv/run_conversion-perl_import_pl.sh.j2"
    dest="{{ kohalxcs_kohalxc_tooldir }}/ppmmtws/ConversionTools/run_conversion.sh"
    mode="u+rwx,g+rx,o-rwx"
    backup="yes"
  when:
    - kohalxcs_dataenv_enabled

## Ensure 'run_conversion' script is symlinked to container $HOME/bin
# [KohaLXC]:srvenv
- name: dataenv - Symlink conversion main script in container HOME/bin
  file: >
    src="{{ kohalxcs_kohalxc_tooldir }}/ppmmtws/ConversionTools/run_conversion.sh"
    dest="{{ '/home/'~ansible_user~'/bin/run_conversion' }}"
    state="link"
    force="yes"
  when:
    - kohalxcs_dataenv_enabled


## !! For debug/dev FAIL here on purpose..!! ##
#- fail:
