---
# File: roles/hostnode/defaults/main.yml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
#
# Description: define defaults for all variables used in this role
# - General, KohalXC-tooling, Server-updates, Security, LVM, ZFS, LXCs
# - vars should be named like 'hostnode_var1' etc..
# - vars used in templates for config files should be at target OS defaults
#
# See also:
# - roles/hostnode/vars/main.yaml ('constantized' vars..)
# - <inventory>/group_vars/{all/}{main,vault}.yaml (inventory vars..)
# - <playbooks>/group_vars/{all,hostnode}/{main,vault}.yaml (top-level)
# #############################################################################

## Just to test/debug the inheritance in ansible playbooks..
hostnode_testvar: roles_hostnode_defaults_main.yaml

## #########################
## General: facts & handlers
## #########################
# Facts gathering: False/True
gather_facts: False
# Force all handlers always (also in case play fails etc):
#force_handlers: false
# Local/management user home directory
#local_home: "{{ lookup('env', 'HOME') }}"

## #######################
## Server: KohaLXC tooling
## #######################
# - defaults in 'roles/common/defaults/main.yaml'
# - override these in inventory/group+host_vars
## KohaLXC: works
hostnode_kohalxc_works: "{{ kohalxc_install }}"
## KohaLXC: rootdir
hostnode_kohalxc_rootdir: "{{ hostnode_kohalxc_works }}/KohaLXC"
## KohaLXC: tooldir
hostnode_kohalxc_tooldir: "{{ hostnode_kohalxc_rootdir }}/kohatools"
## KohaLXC: organization
hostnode_kohalxc_organization: "{{ kohalxc_organization }}"

## KohaLXC/devenv: role default
hostnode_devenv_enabled: true
#hostnode_devenv_config: "{{ hostnode_kohalxc_tooldir }}/conf.d/env.dev"
#hostnode_kohalxc_devenv: "{{ kohalxc_devenv }}"

## KohaLXC/srvenv: role default
hostnode_srvenv_enabled: true
# Packages needed for srvenv setup/config/tools
hostnode_srvenv_pckgs:
  - sshfs
#hostnode_srvenv_config: "{{ hostnode_kohalxc_tooldir }}/conf.d/env.srv"
#hostnode_kohalxc_srvenv: "{{ kohalxc_srvenv }}"

## KohaLXC/dataenv: role default
hostnode_dataenv_enabled: true
# KohaLXC/dataenv: datadir
hostnode_dataenv_datadir: "{{ hostnode_kohalxc_works }}/{{ hostnode_kohalxc_organization }}/kohadata"
# KohaLXC/dataenv: datasets name(s) for MMT-migration:
hostnode_dataenv_dataset: "{{ kohalxc_dataset }}"
# KohaLXC/dataenv: dataset source dir for MMT
hostnode_dataenv_datasrc: source

# KohaLXC/mmtenv: support creation of data+mmt-aware LXCs
# - by default enable here if dataenv_dataset(s) have been defined in the host
hostnode_mmtenv_enabled: "{{ (hostnode_dataenv_dataset is defined and hostnode_dataenv_dataset.0 is defined) | ternary('true','false') }}"
# KohaLXC/mmtenv: PP/MMT-tool environment
hostnode_ppmmtenv_enabled: "{{ hostnode_mmtenv_enabled | d('false') }}"
# KohaLXC/mmtenv: Origo/MMT-tool environment
hostnode_origommtenv_enabled: false

## ###########################
## Server: updates/reboots/nic
## ###########################
# Rebootable server
hostnode_reboot_enabled: false
# Upgradable server
hostnode_upgrade_enabled: false
# Pattern to ignore pckgs from upgrades
hostnode_upgrade_pckgsignore:
# Network-card interface
hostnode_network_interface: eth0

## #########################
## Server security/hardening 
## #########################
## Secure/hardening of the server
hostnode_secure_enabled: false
## 00 - packages needed for security/hardening
hostnode_secure_pckgs:
  - openssh-client
  - openssh-server
## 17 - Analyze system logs
# Enable reports always when the script is run
hostnode_secure_logwatch_always: false
# Logwatch packges
hostnode_secure_logwatch_pckgs:
  - logwatch
  - libdate-manip-perl
  - libsys-cpu-perl
  - libsys-meminfo-perl
# Output type: [stdout], mail
hostnode_secure_logwatch_output: mail
# Format of the report: [text], html
hostnode_secure_logwatch_format: html
# Range of the report: All, Today, [Yesterday]
hostnode_secure_logwatch_range: All
# Level of the report: [Low (0)], Med (5), High (10)
hostnode_secure_logwatch_detail: High
# Period to report (default: All)
hostnode_secure_logwatch_reportperiod: 30
# Where to report (email-address):
# - @gmail addresses do not seem to work, probably cause/if
#   the server only has 'mailutils' installed
hostnode_secure_logwatch_reportemail: webmaster@localhost

###############
## Storage: LVM
###############
## LVM support: false/true
hostnode_lvm_enabled: false
# LVM-related packages
hostnode_lvm_pckgs:
  - lvm2

# Volume group (VG) name: e.g /dev/roi1_vg 
hostnode_lvmvg: host_vg 
# Logical volume for host OS (root): /dev/roi1_vg/root
hostnode_lvmlv_os: root 
# Logical volume size for host OS (root)
hostnode_lvmlv_os_size: 80G
# Logical volume for data (containers): /dev/roi1_vg/data
hostnode_lvmlv_data: data 
# Logical volume size for (containers) dir-data
hostnode_lvmlv_data_size: +100%FREE
# Filesystem for LV/data
hostnode_lvmlv_data_fs: ext4
# Logical volume for zfspool (containers): /dev/roi1_vg/tank
hostnode_lvmlv_tank: tank 
# Logical volume size for (containers) zfspool-data
hostnode_lvmlv_tank_size: +100%FREE
# Volume/zpool-name for LV/tank
hostnode_lvmlv_tank_fs: zfstank
# Logical volume for swap: /dev/roi1_vg/swap_1
hostnode_lvmlv_swap: swap_1 
# Logical volume size for swap (e.g RAM size)
hostnode_lvmlv_swap_size: 128G 

###############
## Storage: ZFS
###############
## ZFS support: true/false
hostnode_zfs_enabled: false
# ZFS-related packages
hostnode_zfs_pckgs:
  - zfsutils-linux

# ZFS/zpool name
hostnode_zfs_zpool: "{{ hostnode_lvmlv_tank_fs | d('zfstank') }}"
# ZFS LXC-root filesystem in LV-'tank'/zpool for LXC-containers'
hostnode_zfs_rootdir: lxc

## ###############
## LXC-environment
## ###############
## Koha/hosts LXC-environment: false/true
hostnode_lxcenv_enabled: true

## LXC networking:  manual (configured) / dynamic (dhcp)
hostnode_lxcenv_networking: dhcp
#hostnode_lxcenv_networking: manual
# LXC-network domain name: none, lxc, weblxc, mdblxc
hostnode_lxcenv_domain:

## Koha-host/lxc-environment filesystem/storage defaults:
# Container rootfs path (folder where LXCs are placed)
hostnode_lxcenv_lxcpath: /var/lib/lxc
# Container ZFS-rootfs path (folder where ZFS-enabled LXCs are placed)
hostnode_lxcenv_zfspath: /var/lib/zfslxc
# Container rootfs partition minimum size (if partitioned)
hostnode_lxcenv_rootfs_size: 100G
# Container backing store (dir/zfs/lvm/btrfs..)
hostnode_lxcenv_bdev: dir
# Container zfsroot backing store (in case bdev is 'zfs')
hostnode_lxcenv_zfsroot: "{{ hostnode_zfs_zpool }}/{{ hostnode_zfs_rootdir }}"

## Container logging
# - log directory: server <devops>/log -dir
hostnode_lxcenv_logdir: "/home/{{ kohalxc_operuser | d('ubuntu') }}/log"
# - log file: kohalxc-ansible.log
hostnode_lxcenv_logfile: "{{ hostnode_lxcenv_logdir }}/kohalxc-ansible.log"
# - log_level: INFO/DEBUG
hostnode_lxcenv_loglevel: DEBUG

## ##########################
## LXC: defaults/provisioning
## ##########################

## LXC: mount entries
# - kohatools
hostnode_lxc_mount_kohatools: lxc.mount.entry = /home/{{ hostnode_operuser }}/Works/KohaLXC/kohatools home/{{ kohalxc_operuser }}/kohatools none bind,create=dir 0 0
# - kohadata
hostnode_lxc_mount_kohadata: lxc.mount.entry = /home/{{ hostnode_operuser }}/Works/{{ kohalxc_organization }}/kohadata/dump4mmt-{{ hostnode_dataenv_dataset.0 | d('default') }} home/{{ kohalxc_operuser }}/kohadata none bind,create=dir 0 0
hostnode_lxc_mounts:
  - "{{ hostnode_lxc_mount_kohatools }}" 
  - "{{ hostnode_lxc_mount_kohadata }}"

## LXC: groups
hostnode_lxc_groups:
  - lxc.group = {{ hostnode_lxcenv_domain | d('lxc') }}

## LXC: start
hostode_lxc_starts:
  - lxc.start.auto = 0
  - lxc.start.delay = 0

## LXC: container_command
# - common LXC-setups to run during Ansible/lxc-create:
hostnode_lxc_container_command: |
  addgroup --gid "{{hostnode_kohagrp_gid}}" "{{hostnode_kohagrp_name}}"
  usermod -a -G "{{hostnode_kohagrp_name}}" `getent passwd 1000 | cut -d: -f1`
  mkdir -p {{ hostnode_lxcenv_logdir }}
  touch {{ hostnode_lxcenv_logfile }}
  id | tee -a {{ hostnode_lxcenv_logfile }}
  chown -R 1000:1000 {{ hostnode_lxcenv_logdir }}
  echo "== kohalxc [ansible:lxc_create]: Playbook:'kohalappi' in roles/hostnode/defaults/main.yaml)" | tee -a {{ hostnode_lxcenv_logfile }}
  echo "== kohalxc [ansible:lxc_create]: `date`" | tee -a {{ hostnode_lxcenv_logfile }}
  env | grep KOHA | {{ hostnode_lxcenv_logfile }}
  echo "== kohalxc [ansible:lxc_create]: Use '{{ hostnode_lxcenv_networking }}' scheme for IP-addresses in LXC-net.." | tee -a {{ hostnode_lxcenv_logfile }}
  [[ "manual" == "{{ hostnode_lxcenv_networking }}" ]] && sed -i "s/iface eth0 inet dhcp/iface eth0 inet manual/" /etc/network/interfaces
  [[ "dhcp" == "{{ hostnode_lxcenv_networking }}" ]] && sed -i "s/iface eth0 inet manual/iface eth0 inet dhcp/" /etc/network/interfaces
  echo "== kohalxc [ansible:lxc_create]: Contents of: /etc/network/interfaces:" | tee -a {{ hostnode_lxcenv_logfile }}
  cat /etc/network/interfaces | tee -a {{ hostnode_lxcenv_logfile }}
  ifconfig -a | tee -a {{ hostnode_lxcenv_logfile }}

# - container command: kohalxc/mdbenv pckgs installation
# MariaDB-5.5/Mysql-5.5 non-interactive installation (debconf/apt-get)
hostnode_mdbenv_pckginstall: |
  echo "== kohalxc [ansible:mdbenv]: Debconf for non-interactive install of database server (MariaDB-5.5)" | tee -a {{ hostnode_lxcenv_logfile }}
  debconf-set-selections <<< "mariadb-server-5.5 mysql-server/root_password password"
  debconf-set-selections <<< "mariadb-server-5.5 mysql-server/root_password_again password"
  echo "== kohalxc [ansible:mdbenv]: Installing database server (MariaDB-5.5)" | tee -a {{ hostnode_lxcenv_logfile }}
  DEBIAN_FRONTEND=noninteractive apt-get -q -y install mariadb-server-5.5
  mysqladmin ping status -u root | tee -a {{ hostnode_lxcenv_logfile }}

## LXC: template
# - template (distro): Ubuntu
hostnode_lxc_tmpl: ubuntu
# - template/release: Trusty 14.04 LTS
hostnode_lxc_tmpl_release: trusty
# - template/packages: installed to all LXCs
hostnode_lxc_tmpl_pckgs: "wget,joe,nano,python2.7-minimal,git,tig"
# - template/auth_key:
hostnode_lxc_tmpl_authkey: ".ssh/id_rsa.pub"

## LXC: lists of containers
# Default LXCs (list-of-dicts), leave undefined for now:
#hostnode_lxc_defaults:

# All LXCs (how to empty the lists/dicts here):
#hostnode_lxcs: {} # empty dict, flow mapping (with_dict)
#hostnode_lxcs: [] # empty hash, block mapping (with_items)

# How to define a list of containers at role/defaults level:
#hostnode_lxcs:
#  - "{{ kldev_dmdbks }}"
