---
# File: roles/common/defaults/main.yaml
# #############################################################################
# Code is part of KohaLXC/kohatools Ansible/Bash tooling environment  
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
#
# Description:
# - defaults of vars that should/could be made available to other roles
# - General and KohaLXC: (devenv, srvenv, mdbenv, webenv)
# Note: to use these just include this 'common'-role in the plays
# #############################################################################

###########
# General #
###########
# Facts gathering: False/True
gather_facts: True
# Local/management user home directory
local_home: "{{ lookup('env', 'HOME') }}"

###################
# KohaLXC-tooling #
###################
## Koha-LXC operations account
# -user name:
kohalxc_operuser: ubuntu
# -user pass:
#kohalxc_operpass:
# -Git user
kohalxc_gituser_name: kohadev
# -Git user email
kohalxc_gituser_email: "{{ kohalxc_gituser_name | d('anon') }}@open.org.fake"
# -Git user
kohalxc_author: "Koha Developer"

## KohaLXC-toolset
# KohaLXC-installation (target host) directory:
#kohalxc_install: "/home/{{ ansible_user }}/Works"
# KohaLXC-works source directories (from the host env w/ defaults):
kohalxc_works: "{{ lookup('env', 'KOHALXC_WORKS') }}"
# KohaLXC-root directory (kohalxc_root): 
kohalxc_rootdir: "{{ lookup('env', 'KOHALXC_ROOTDIR') | d(kohalxc_works~'/KohaLXC', true) }}"
# KohaLXC-kohatools directory (kohalxc_tools):
kohalxc_tooldir: "{{ lookup('env', 'KOHALXC_TOOLDIR') | d(kohalxc_rootdir~'/kohatools', true) }}"
# KohaLXC-organization (kohalxc_org): KohaSuomi, KohaLappi, ect.
kohalxc_organization: "{{ lookup('env', 'KOHALXC_ORGANIZATION') | d('KohaSuomi', true) }}"
# KohaLXC-setup directory (kohalxc_setups):
kohalxc_setupdir: "{{ lookup('env', 'KOHALXC_SETUPDIR') | d(kohalxc_works~'/'~kohalxc_organization~'/kohalxc', true) }}"
# Database/data directory (kohalxc_datas):
kohalxc_datadir: "{{ lookup('env', 'KOHALXC_DATADIR') | d(kohalxc_works~'/'~kohalxc_organization~'/kohadata', true) }}"
# Database dataset(s): (kohalxc_dataset: name, date, content of the dump)
kohalxc_dataset: "{{ lookup('env', 'KOHALXC_DATASET') | d({}, true) }}"
# - "{{ lookup('env', 'KOHALXC_DATASET') | d([], true) }}"
kohalxc_datasets:
- { name: "{{ lookup('env', 'KOHALXC_DATASET') | d({}, true) }}" }

## KohaLXC-devenv: developer env config files and setup scripts
kohalxc_devenv: "{{ kohalxc_tooldir }}/conf.d/env.dev"
kohalxc_devenv_enabled: (hostnode_devenv_enabled is defined and hostnode_devenv_enabled) or (kohalxcs_devenv_enabled is defined and kohalxcs_devenv_enabled)
## TODO: above fixes Ansible warning about when:/defs having Jinja2-delimiters
#kohalxc_devenv_enabled: "{{ (hostnode_devenv_enabled is defined and hostnode_devenv_enabled) or (kohalxcs_devenv_enabled is defined and kohalxcs_devenv_enabled) }}"

## KohaLXC-srvenv: common server env config files and setup scripts
kohalxc_srvenv: "{{ kohalxc_tooldir }}/conf.d/env.srv"
kohalxc_srvenv_enabled: false

## KohaLXC-mdbenv: maria/mysql db env config files and setup scripts
kohalxc_mdbenv: "{{ kohalxc_tooldir }}/conf.d/env.mdb"
kohalxc_mdbenv_enabled: false

## KohaLXC-webenv: (koha)webapp env config files and setup scripts
kohalxc_webenv: "{{ kohalxc_tooldir }}/conf.d/env.web"
kohalxc_webenv_enabled: false

## KohaLXC-dataenv: (koha/conversion)data source, configs and tools scripts
kohalxc_dataenv: "{{ kohalxc_tooldir }}/conf.d/env.data"
kohalxc_dataenv_enabled: false

## KohaLXC-lxcenv:
#kohalxc_lxcenv: "{{ kohalxc_tooldir }}/conf.d/env.lxc"
kohalxc_lxcenv_enabled: false
