
# File: group_vars/weblxc
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3
# 
# Description:
# - playbook-level variables for 'weblxc' group of hosts (dynamic remote LXCs)
# #############################################################################

## Proxy-command to enable access to containers directly from management host
# - 'hostnode_operuser' is the mngmt-host dev/ops user
ansible_ssh_common_args: '-o ProxyCommand="ssh -q {{ hostnode_operuser }}@{{ hostnode_websrv }} -p {{ hostnode_sshport }} -W %h:%p"'
