---
# File: roles/hostnode/vars/lxcs/lxc-kldev_dmdb.yaml
# #############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
#
# Description:
# - LXC-name: 'kldev_dmdb.weblxc'
# - kldev: KohaLappi/development, Ubuntu/Trusty, dir, lxcbr0/NAT
# - dmdb: data/MMT-conversion + MariaDB (later  "+ Apache2")
# - weblxc: deploy to host serving '*weblxc'-domains
# - network: app(OPAC)-port=88, int(staff)-port=8088
# #############################################################################

## Network LXC/host port mappings + domain:
# - (web/mdb)lxc => host: 88/8088 => 80/8080
net:
  app_port: 88
  int_port: 8088
  domain: weblxc
  srvname: "{{ hostnode_kohaenv_srvname | d('localhost') }}"
  user: "{{ kohalxc_operuser }}"
## lxc: MariaDb (mdbenv), data (dataenv), Apache2/KS316 (webaenv)
# - for MMT/conversion & Koha-deployment (development, dhcp/weblxc)
lxc:
  name: kldev_dmdb
  state: started
  backing_store: "{{ lxc_default.backing_store }}"
  container_log: "{{ lxc_default.container_log }}"
  container_log_level: "{{ lxc_default.container_log_level }}"
  container_config: 
    # lxc/mounts
    - "{{ hostnode_lxc_mount_kohatools }}"
    - "{{ hostnode_lxc_mount_kohadata }}"
    # lxc_groups:
    #- lxc.group = {{ hostnode_environment | d('local') }}
    - lxc.group = development
    - lxc.group = dev
    #- lxc.group = mdb
    - lxc.group = data
    - lxc.group = ppmmt
    # lxc_start:
    - lxc.start.auto = 1
    - lxc.start.delay = 0
    - lxc.start.order = 0
    # lxc_network:
    - lxc.network.veth.pair = Vkldev_dmdb
    - lxc.network.type = veth
    - lxc.network.link = lxcbr0
    - lxc.network.flags = up
  template: "{{ lxc_default.template }}"
  template_options: >
    --user {{ kohalxc_operuser }}
    {{ lxc_default.template_options }}
  container_command:
    "{{ lxc_default.container_command + hostnode_mdbenv_pckginstall }}"
