---
# File: group_vars/all/main.yaml
# ##############################################################################
# Code is part of the KohaLXC/kohatools Ansible/Bash tooling environment
# for Koha/ILS-development, deployment & database conversion/migration tasks.
#
# Author: Jukka Aaltonen, Koha-Lappi, Rovaniemi City Library, Lapland/Finland.
# License: GNU General Public License version 3.
# 
# Description:
# - list here all playbook-level 'group_vars' used in inventories/roles setups
#
# See also: (inventory/)<hostnode_environment>/group_vars/all
# Note: setting var here will override the values in the 'inventory'
# ##############################################################################

## Name of the inventory environment for all 'hostnode/LXCs' playbooks:
# - localdev, development, testing, monitoring, production
#hostnode_environment: default

#############
## General ##
#############

# Facts gathering:
#gather_facts: False
# Force all handlers always (also in case play fails etc):
#force_handlers: false

#########
## LVM ##
#########

# LVM enablement:  (usually only in testing/production)
#hostnode_lvm_enabled: false

################################################################
## Vault/secure settings:
# - list here all encrypted variable names needed by the play
# - use '*vault*.yaml' etc. (won't be included in this repo)
################################################################

## Settings for accessing Koha/LXC-containers
# Koha-user account (LXC): 'ubuntu'
# - could be overriden in lxc-create
kohalxc_operuser: ubuntu
# Koha-user account (LXC) pass
kohalxc_operpass:

## Settings for "devenv", "mdbenv", "kohaenv" users/passes/configs
# Maria/Mysql-database root user: 'mdbenv_dbroot'
mdbenv_rootuser: root
# Maria/Mysql-database root user pass: 'mdbenv_dbpass'
mdbenv_rootpass:
# Koha-database user: 'koha'
mdbenv_kohauser: koha
# Koha-database pass
mdbenv_kohapass:
# Koha-database name
mdbenv_kohadb: kohadata

# Koha-(local)developer user: system '$USER' or 'ansible_user'
localdev_user: "{{ ansible_user }}" 
# Koha-(local)developer user pass
localdev_pass:
  
## Settings for 'testing'/'production' koha-server/hosts
# Server name of "koha" web/applications and services:
hostnode_websrv:
# Server name of "koha" databases and services:
hostnode_mdbsrv:
# Server name of "koha" data/mmt storage/utilities:
hostnode_datasrv:

# Koha-system user id:
hostnode_sysid: 1000
# Koha-system user name:
hostnode_sysuser: kohasys
# Koha-system user pass:
hostnode_syspass:

# Koha-group name:
hostnode_groupname: koha
# Koha-group gid:
hostnode_groupgid: 1001

# Koha-devops user id:
hostnode_operid: 1002
# Koha-devops user name:
hostnode_operuser: kohadev
# Koha-devops pass:
hostnode_operpass:
